После теории вам осталось только в качестве практики выполнить небольшое задание для закрепления навыков.  Все просто:

1.   Изучите код генерации датафрейма, который был опущен в ходе скринкаста;
2.   Выполните все те же действия, которые мы проделывали во время видео. 

Задание не нужно сдавать на проверку, но тем не менее, для закрепления полученных знаний и наработки опыта очень важно его выполнить.
Для уточнения раскрываю второй пункт:
1.   Сгенерировать исходные данные;
2.   С помощью модуля Pandas сохранить данные в csv, в сжатый csv, а затем прочитать из каждого файла, выведя дополнительно с помощью %%time затраченное время на каждую из операций.
3.   Повторить действия из пункта 2 с модулем PyArrow;
4.   Cравнить ваши временные значения с полученными в ходе видео и также место, занимаемое каждой группой файлов.

Уверен, вам всем горы по колено. Успехов в выполнении практического задания! Вы справитесь!

In [ ]:
import random
import string
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.csv as pa_csv
from datetime import datetime

In [ ]:
def gen_random_string(length: int = 32) -> str:
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))

In [ ]:
def gen_random_df() -> pd.core.frame.DataFrame:
    dt = pd.date_range(start=datetime(2000, 1, 1), end=datetime(2021, 1, 1), freq='min')

    np.random.seed = 42
    df_size = len(dt)

    return pd.DataFrame({
        'date': dt,
        'a': np.random.rand(df_size),
        'b': np.random.rand(df_size),
        'c': np.random.rand(df_size),
        'd': np.random.rand(df_size),
        'e': np.random.rand(df_size),
        'str1': [gen_random_string() for x in range(df_size)],
        'str2': [gen_random_string() for x in range(df_size)]
    })

In [ ]:
%%time
df = gen_random_df()

CPU times: user 3min 4s, sys: 2.66 s, total: 3min 6s
Wall time: 3min 7s

In [ ]:
df.head()

,date,a,b,c,d,e,str1,str2
0,2000-01-01 00:00:00,0.125011,0.213991,0.874248,0.650692,0.890806,IPHQEIHF47JE3TVGK9NV8PEVIFU3QNRM,4JCPUYNF2S6K18GT4GHG09ZO7JF9SJIT
1,2000-01-01 00:01:00,0.240762,0.643738,0.843214,0.087027,0.997840,JK8GCCEXN7ZFOSCZG61YEFVCMAWQ6POR,BY5T5YW3JBAN4AHR19IDDVL3YEPL23VA
2,2000-01-01 00:02:00,0.811978,0.777474,0.771122,0.301199,0.737956,ZAJRX9CULVNGMB1NDZM70N44E5I5E9IZ,PXVNSI4455UPC8JN15GXSPOB4P3SS50N
3,2000-01-01 00:03:00,0.752441,0.977780,0.035401,0.479142,0.135979,53DW39RGGSDSLKN9069RR22509YHB9Y7,XQ8IMZ5NBKZVV5TYJA0NYKAKBRDCDE7C
4,2000-01-01 00:04:00,0.982029,0.408427,0.358891,0.074738,0.484785,BEFS2UMKCW3XE5K5MLDPXNW7DFXQXMVO,G359C273HV3VI57LNQX7S6IQGKG65OJ4

In [ ]:
df.shape

(11046241, 8)

In [ ]:
%%time

df.to_csv('csv_pandas.csv', index=False)

CPU times: user 2min 18s, sys: 4.45 s, total: 2min 22s
Wall time: 2min 25s

In [ ]:
%%time

df.to_csv('csv_pandas.csv.gz', index=False, compression='gzip')

CPU times: user 6min 16s, sys: 3.43 s, total: 6min 20s
Wall time: 6min 20s

In [ ]:
%%time

df = gen_random_df()

CPU times: user 1min 39s, sys: 1.58 s, total: 1min 40s
Wall time: 1min 41s

,date,a,b,c,d,e,str1,str2
0,2000-01-01 00:00:00,0.599786,0.843718,0.405022,0.058568,0.987571,K40KFX5WFJUM36S68TOQZBJ7DC8KPC2I,FBQCS1H19PO7ASYQ256NG09QDZTNTJM2
1,2000-01-01 00:01:00,0.588556,0.180284,0.813070,0.809731,0.554659,QYD03TA55STWF26F4GMLPFQ4J473LZCU,GY3L0HCWMUC6BYIJ7NRN7312QSIUD6Q4
2,2000-01-01 00:02:00,0.584001,0.413550,0.805196,0.674698,0.726246,LHKBQEMCJB8Z7X52SF6PDNQ89X1D0T8L,RDRNGO4WSPDVSR2PMIPNTTLO8B7VDLCQ
3,2000-01-01 00:03:00,0.085875,0.488474,0.547745,0.551928,0.716217,2T2MIA0GO3TRL5N24FQVRYQJ2EF2SIM3,6CFIWVMW5Q2JHUUBD27JCPW78QJ7TYMX
4,2000-01-01 00:04:00,0.996766,0.293544,0.878246,0.629403,0.873490,4WW7JRKNAJUDN8YROURSEWUN4DMYKPP2,QY13L54RYLT1QY4GY5GSWM4ZH9KC8HB5

In [ ]:
df.head()

,date,a,b,c,d,e,str1,str2
0,2000-01-01 00:00:00,0.599786,0.843718,0.405022,0.058568,0.987571,K40KFX5WFJUM36S68TOQZBJ7DC8KPC2I,FBQCS1H19PO7ASYQ256NG09QDZTNTJM2
1,2000-01-01 00:01:00,0.588556,0.180284,0.813070,0.809731,0.554659,QYD03TA55STWF26F4GMLPFQ4J473LZCU,GY3L0HCWMUC6BYIJ7NRN7312QSIUD6Q4
2,2000-01-01 00:02:00,0.584001,0.413550,0.805196,0.674698,0.726246,LHKBQEMCJB8Z7X52SF6PDNQ89X1D0T8L,RDRNGO4WSPDVSR2PMIPNTTLO8B7VDLCQ
3,2000-01-01 00:03:00,0.085875,0.488474,0.547745,0.551928,0.716217,2T2MIA0GO3TRL5N24FQVRYQJ2EF2SIM3,6CFIWVMW5Q2JHUUBD27JCPW78QJ7TYMX
4,2000-01-01 00:04:00,0.996766,0.293544,0.878246,0.629403,0.873490,4WW7JRKNAJUDN8YROURSEWUN4DMYKPP2,QY13L54RYLT1QY4GY5GSWM4ZH9KC8HB5

In [ ]:
df.shape

(11046241, 8)

Pandas

In [ ]:
%%time

df.to_csv('csv_pandas.csv', index=False)

CPU times: user 1min 44s, sys: 2.77 s, total: 1min 47s
Wall time: 1min 48s

In [ ]:
%%time

df.to_csv('csv_pandas.csv.gz', index=False, compression='gzip')

CPU times: user 4min 42s, sys: 1.97 s, total: 4min 44s
Wall time: 4min 45s

In [ ]:
%%time

df1 = pd.read_csv('csv_pandas.csv')

CPU times: user 24.7 s, sys: 4.32 s, total: 29.1 s
Wall time: 29.5 s

In [ ]:
%%time

df2 = pd.read_csv('csv_pandas.csv.gz')

CPU times: user 33.7 s, sys: 3.36 s, total: 37.1 s
Wall time: 37.6 s

PyArrow

In [ ]:
df_pa = df.copy()

In [ ]:
df_pa['date'] = df_pa['date'].values.astype(np.int64) // 10 ** 9

In [ ]:
df_pa.head()

,date,a,b,c,d,e,str1,str2
0,946684800,0.599786,0.843718,0.405022,0.058568,0.987571,K40KFX5WFJUM36S68TOQZBJ7DC8KPC2I,FBQCS1H19PO7ASYQ256NG09QDZTNTJM2
1,946684860,0.588556,0.180284,0.813070,0.809731,0.554659,QYD03TA55STWF26F4GMLPFQ4J473LZCU,GY3L0HCWMUC6BYIJ7NRN7312QSIUD6Q4
2,946684920,0.584001,0.413550,0.805196,0.674698,0.726246,LHKBQEMCJB8Z7X52SF6PDNQ89X1D0T8L,RDRNGO4WSPDVSR2PMIPNTTLO8B7VDLCQ
3,946684980,0.085875,0.488474,0.547745,0.551928,0.716217,2T2MIA0GO3TRL5N24FQVRYQJ2EF2SIM3,6CFIWVMW5Q2JHUUBD27JCPW78QJ7TYMX
4,946685040,0.996766,0.293544,0.878246,0.629403,0.873490,4WW7JRKNAJUDN8YROURSEWUN4DMYKPP2,QY13L54RYLT1QY4GY5GSWM4ZH9KC8HB5

In [ ]:
%%time

df_pa_table = pa.Table.from_pandas(df_pa)

CPU times: user 1.62 s, sys: 1.27 s, total: 2.89 s
Wall time: 2 s

In [ ]:
%%time

pa_csv.write_csv(df_pa_table, 'csv_pyarrow.csv')

CPU times: user 7.6 s, sys: 514 ms, total: 8.11 s
Wall time: 8.49 s

In [ ]:
%%time

with pa.CompressedOutputStream('csv_pyarrow.csv.gz', 'gzip') as out:
    pa_csv.write_csv(df_pa_table, out)

CPU times: user 1min 51s, sys: 804 ms, total: 1min 52s
Wall time: 1min 53s

In [ ]:
%%time

df_pa_1 = pa_csv.read_csv('csv_pyarrow.csv')

CPU times: user 9.65 s, sys: 5.73 s, total: 15.4 s
Wall time: 5.82 s

In [ ]:
%%time

df_pa_2 = pa_csv.read_csv('csv_pyarrow.csv.gz')

CPU times: user 15.6 s, sys: 2.08 s, total: 17.7 s
Wall time: 10.2 s

Parquet

In [ ]:
%%time

table = pa.Table.from_pandas(df)

CPU times: user 2.06 s, sys: 1.02 s, total: 3.09 s
Wall time: 3.4 s

In [ ]:
%%time

import pyarrow.parquet as pq

pq.write_table(table, 'df.parquet')

CPU times: user 3.22 s, sys: 616 ms, total: 3.84 s
Wall time: 4.29 s

In [ ]:
table.schema

date: timestamp[ns]
a: double
b: double
c: double
d: double
e: double
str1: string
str2: string
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 1113

In [ ]:
table.shape

(11046241, 8)

In [ ]:
table

pyarrow.Table
date: timestamp[ns]
a: double
b: double
c: double
d: double
e: double
str1: string
str2: string
----
date: [[2000-01-01 00:00:00.000000000,2000-01-01 00:01:00.000000000,2000-01-01 00:02:00.000000000,2000-01-01 00:03:00.000000000,2000-01-01 00:04:00.000000000,...,2020-12-31 23:56:00.000000000,2020-12-31 23:57:00.000000000,2020-12-31 23:58:00.000000000,2020-12-31 23:59:00.000000000,2021-01-01 00:00:00.000000000]]
a: [[0.5997858758344955,0.5885555258514964,0.5840008817763518,0.08587459627290517,0.9967657749523905,...,0.8726155059893503,0.7330322667805145,0.21505787159052625,0.137215243391288,0.8277330622881067]]
b: [[0.8437178092793546,0.18028366196881307,0.41355007178201797,0.48847431252232576,0.29354437490029495,...,0.0793701670757051,0.05674380011584923,0.1292805884812559,0.08929183775803728,0.38340409872471026]]
c: [[0.40502194601082553,0.8130700568807623,0.8051960100063827,0.5477450525112162,0.8782461943500995,...,0.6495000698270724,0.40874832097107083,0.6929793715859363,0.1574431288746302,0.7979267850278988]]
d: [[0.05856836753080219,0.8097307516810697,0.6746984760971665,0.5519281131997862,0.6294025575585851,...,0.48112338626522944,0.7386085002367627,0.6010419588968084,0.7333559994088115,0.9840922818940545]]
e: [[0.9875714842824914,0.5546588283735663,0.7262459827596266,0.7162168912470082,0.8734900886591715,...,0.7765772973800447,0.5311577214608312,0.7015517229045424,0.08056536830577754,0.6938316907438208]]
str1: [["K40KFX5WFJUM36S68TOQZBJ7DC8KPC2I","QYD03TA55STWF26F4GMLPFQ4J473LZCU","LHKBQEMCJB8Z7X52SF6PDNQ89X1D0T8L","2T2MIA0GO3TRL5N24FQVRYQJ2EF2SIM3","4WW7JRKNAJUDN8YROURSEWUN4DMYKPP2",...,"TFZVM5YD09M4D3L2YP70BXN41NCAOTPI","LTFRD75OZ8ABOWGG9EEZDUCPXBHLSO2V","M2YTCRCHWIGULTE10BH8BYRG5P5LTEJK","LHFLPQGTOVMBNLLR6WZLWJUJ8MTPBHGL","IY4NEXPQH4T7SLN956Z03SVXTHEDPD2I"]]
str2: [["FBQCS1H19PO7ASYQ256NG09QDZTNTJM2","GY3L0HCWMUC6BYIJ7NRN7312QSIUD6Q4","RDRNGO4WSPDVSR2PMIPNTTLO8B7VDLCQ","6CFIWVMW5Q2JHUUBD27JCPW78QJ7TYMX","QY13L54RYLT1QY4GY5GSWM4ZH9KC8HB5",...,"R3B5BD3P5TRQAW323WTXEO4MRX0L02KG","SNN1TZ879D96ILJ556FA5LD9CYXBLH3D","IY7ZRT3M71740WXMOMGSO02NX1XE82FX","4T968C7JPNQWXL5L0O0A0TLXT8SX1UJG","2DG8AU6GLXRCHTIJA88B009YWI8GIOAC"]]

In [ ]:
%%time

table2 = pq.read_table('df.parquet')

CPU times: user 3 s, sys: 8.06 s, total: 11.1 s
Wall time: 8.79 s

In [ ]:
table2.shape

(11046241, 8)

In [ ]:
table2

pyarrow.Table
date: timestamp[us]
a: double
b: double
c: double
d: double
e: double
str1: string
str2: string
----
date: [[2000-01-01 00:00:00.000000,2000-01-01 00:01:00.000000,2000-01-01 00:02:00.000000,2000-01-01 00:03:00.000000,2000-01-01 00:04:00.000000,...,2000-04-01 00:27:00.000000,2000-04-01 00:28:00.000000,2000-04-01 00:29:00.000000,2000-04-01 00:30:00.000000,2000-04-01 00:31:00.000000],[2000-04-01 00:32:00.000000,2000-04-01 00:33:00.000000,2000-04-01 00:34:00.000000,2000-04-01 00:35:00.000000,2000-04-01 00:36:00.000000,...,2000-07-01 00:59:00.000000,2000-07-01 01:00:00.000000,2000-07-01 01:01:00.000000,2000-07-01 01:02:00.000000,2000-07-01 01:03:00.000000],...,[2020-09-06 20:16:00.000000,2020-09-06 20:17:00.000000,2020-09-06 20:18:00.000000,2020-09-06 20:19:00.000000,2020-09-06 20:20:00.000000,...,2020-12-06 20:43:00.000000,2020-12-06 20:44:00.000000,2020-12-06 20:45:00.000000,2020-12-06 20:46:00.000000,2020-12-06 20:47:00.000000],[2020-12-06 20:48:00.000000,2020-12-06 20:49:00.000000,2020-12-06 20:50:00.000000,2020-12-06 20:51:00.000000,2020-12-06 20:52:00.000000,...,2020-12-31 23:56:00.000000,2020-12-31 23:57:00.000000,2020-12-31 23:58:00.000000,2020-12-31 23:59:00.000000,2021-01-01 00:00:00.000000]]
a: [[0.5997858758344955,0.5885555258514964,0.5840008817763518,0.08587459627290517,0.9967657749523905,...,0.2637949687000447,0.31178558845645243,0.306135425844689,0.1761741800531489,0.5039778697979637],[0.487631170525032,0.9511239945547595,0.7095133870056003,0.9419895850015774,0.713842577068007,...,0.4312696240171585,0.6210972879121561,0.2572648920625451,0.6490426943080204,0.1242776597667038],...,[0.146506802832703,0.38559622413096695,0.5786693643008547,0.007467708818659435,0.6277421154372816,...,0.7590631613002108,0.9073935792792668,0.18193318072241704,0.5436146139372741,0.9125224866301711],[0.7724335124629301,0.4192156030296864,0.6792396383400292,0.12377600236254072,0.752511371987429,...,0.8726155059893503,0.7330322667805145,0.21505787159052625,0.137215243391288,0.8277330622881067]]
b: [[0.8437178092793546,0.18028366196881307,0.41355007178201797,0.48847431252232576,0.29354437490029495,...,0.5105231345960665,0.49972133640092786,0.7001641654412883,0.36747793122497197,0.6751444210759654],[0.8575160816882292,0.04278836813828413,0.7676733982506139,0.1949038991166263,0.31489518569345865,...,0.5392125298493856,0.9409345689684268,0.5845997459744384,0.8837722937443618,0.10460305384479429],...,[0.8767325441250481,0.41366421781927043,0.4722925378520212,0.6878259287481613,0.589899794783825,...,0.2133333962826961,0.5345992697459651,0.7054911248326086,0.6847511205525918,0.8128028288828582],[0.29676130867796546,0.7024371063948212,0.3087666930350146,0.773818593203531,0.6534827580547425,...,0.0793701670757051,0.05674380011584923,0.1292805884812559,0.08929183775803728,0.38340409872471026]]
c: [[0.40502194601082553,0.8130700568807623,0.8051960100063827,0.5477450525112162,0.8782461943500995,...,0.27640637252216305,0.4090865339905051,0.33079104563565953,0.2751890594898265,0.5889871682574515],[0.8498902555736962,0.6593323457015925,0.9364725079602207,0.4770747092179437,0.3999361027431221,...,0.19765755637590188,0.024157152938093396,0.9449892965640857,0.6403367207941818,0.8967562462818611],...,[0.1122932001693151,0.10801330704192968,0.2640123292529961,0.7504255123983296,0.3821686821457416,...,0.26254247762145067,0.9862942865231731,0.7963827770462399,0.927160873071097,0.981112634669147],[0.8229959777086657,0.6777388565262346,0.42841689003394146,0.161590221452088,0.4460778465538976,...,0.6495000698270724,0.40874832097107083,0.6929793715859363,0.1574431288746302,0.7979267850278988]]
d: [[0.05856836753080219,0.8097307516810697,0.6746984760971665,0.5519281131997862,0.6294025575585851,...,0.13212783896181535,0.7339868167369109,0.7431751578794987,0.5707669347785921,0.41412639263714945],[0.9625345956205669,0.5404207479391834,0.773664697578614,0.32313970549193516,0.021281136710861626,...,0.2067807683391053,0.11291217686571586,0.36086248508356145,0.4540739426455024,0.9005461542266573],...,[0.9550061552711804,0.5715452627310348,0.2658596747972397,0.21045129300007392,0.16212626251922313,...,0.9015824415411464,0.9797580256211446,0.6072382013667686,0.42548620084014876,0.7674979933176799],[0.6162035769927777,0.43398310472596624,0.47655746187477344,0.6523980508980991,0.9629021690177928,...,0.48112338626522944,0.7386085002367627,0.6010419588968084,0.7333559994088115,0.9840922818940545]]
e: [[0.9875714842824914,0.5546588283735663,0.7262459827596266,0.7162168912470082,0.8734900886591715,...,0.7749592629522883,0.8530881993266722,0.5572521731366878,0.7274238110795817,0.09026383362035562],[0.5934981125834612,0.9690121231092711,0.6290620731226124,0.21062551833856158,0.20301818704534824,...,0.5549205371064206,0.39364802559220136,0.6014245313937232,0.9424130873445977,0.6122288181140556],...,[0.1868705714506571,0.24957024076422707,0.10382616311342274,0.9058521264465152,0.5587441248847148,...,0.7095371413559156,0.6774829130135062,0.26755008311451656,0.9798143166627793,0.7304222333705999],[0.6088713666594647,0.855784528813029,0.23238259427493602,0.1923660080623294,0.22650894687247436,...,0.7765772973800447,0.5311577214608312,0.7015517229045424,0.08056536830577754,0.6938316907438208]]
str1: [["K40KFX5WFJUM36S68TOQZBJ7DC8KPC2I","QYD03TA55STWF26F4GMLPFQ4J473LZCU","LHKBQEMCJB8Z7X52SF6PDNQ89X1D0T8L","2T2MIA0GO3TRL5N24FQVRYQJ2EF2SIM3","4WW7JRKNAJUDN8YROURSEWUN4DMYKPP2",...,"U5AZH8XK7QF0PPI3I4ZW1N0FG35IKEV2","KYE3P0T7Q54NLR55RHTAT1Z8YX84K3Y3","EDQUZG5OJXJE5L36LG5OEH9E2HY3ALXU","B38RE5J7G1ROLA92UJV82R160HNKMIT2","YNKMBBOY0NZMP8SJWVLMJ0WXCZNRASM6"],["MFC4HCZ0LY1F575F21PG82J9ZJELYC21","S4WR2JEX6VLOS73LN64RFMWYBM3505C6","V037NP8VKN27OKTS2XH38WQFG80AW3LN","BRG9D2IBPLK04H522PFQ4BJR16FM120D","7088482IZRGXH53GC6UQ0G35NCX558NB",...,"8CVO1I8X2GZ58L7UDPHU5DFSCXPFF0T2","0ZVEJTUK14FZK20EEYIF8J8SKXOIQ0RB","RFP5ZPYBSYMNT6Z2VRFKLL8I1HY1HJEP","DQMYBSY3GD5K9BJL5T7BRJWQNW5OBIJC","GRHTE7KS8H9C9DUF9I9KTIKZ9TOKUX25"],...,["I4F5ELVTYWDL4PKGTIWG8U6YDJTBHN1P","2PSZBDBHJGEORXI0Q245RWEUUUSE7MIA","37WJ36U4Z72FMTJE2FWAO10GLVENZV83","K9UFHIML9YB155J7SE51NK44RF07NMLU","XQJB5H4FEZKEC7UDZ3TD4G7LJMV6V86O",...,"WTIOBR7NOIG67BF3O6737OP3FJYVTUMR","5CCHSSVBWPNMHWM1D90LL62R4MDP0JN4","Z53BFZ8PTJ4QZN6IMG6VQN3OPZPXEMXA","N2YHFDBWA76WJ26R0PMXPQQ74L4CF5V1","CDPBRPFOV1RUB3TNNQBOIKQOXQ8TD610"],["RVZ4GRBPG9GIOUAAYZLUUF9H5JWEHOYM","E1K6YXWR9680A5WB98OMSUMVH2SJJR2T","KXCMXJ8SX48JSU3868JM7Y3ML90MM7Z1","STNDLVDYF5E2J14FRRMR3EZFHKKL7VKI","NM66619ONYIUZ3HK4DAHLBFL2SFKF3SV",...,"TFZVM5YD09M4D3L2YP70BXN41NCAOTPI","LTFRD75OZ8ABOWGG9EEZDUCPXBHLSO2V","M2YTCRCHWIGULTE10BH8BYRG5P5LTEJK","LHFLPQGTOVMBNLLR6WZLWJUJ8MTPBHGL","IY4NEXPQH4T7SLN956Z03SVXTHEDPD2I"]]
str2: [["FBQCS1H19PO7ASYQ256NG09QDZTNTJM2","GY3L0HCWMUC6BYIJ7NRN7312QSIUD6Q4","RDRNGO4WSPDVSR2PMIPNTTLO8B7VDLCQ","6CFIWVMW5Q2JHUUBD27JCPW78QJ7TYMX","QY13L54RYLT1QY4GY5GSWM4ZH9KC8HB5",...,"4VW5YLB690VT2O49HJFE3RBANHIH7GAQ","RWRUXUD6CLMPSC0VZ6QAQVTWH6S19FR9","HHMMV3TQI3U5QVIQPNPF7ZHEH94MWK16","75GXRDS6NZIYEUPLSTUGSPP744UUV2VL","EEOOXAPFWEX8KOII6J58C4CH1PGO0MZ9"],["J29MN0RAKBSX89DL48BFA5HBVA0W2O6T","FNES0GZSGQGN383B8DGDUWPUNX6W8BQO","CTMANSEQM2D18DUJ2JKCKTNJA7J120WJ","JVU8QRQG4NFMXGAW1QJKBXRVHMXDSX45","R0I56RG7CROFICJI3LXZL68S2VP8W261",...,"JSEHEPSJA4O15L1ULSE7HWCY8MR87C93","IT1ONLKMM8HSWXUBZVOPUXWTPSB1BEOO","WDHHND85BSZQQ6SWRC0PPJYNIIUF0FX7","SVTDO7NWS49FW3YZ4XB0MRSYRJ1P45JG","650IC2E5GIVQLKUKXD21HORBHSDSK15R"],...,["B285OAENH2IJB5NQTWYF5J6V1UVZA2QH","WGDHOPY2IJ5LYAFOVGJ6BDJU7P3GK8Q0","PGSHRD39UCXJDUFBG64MKJHQLS1X4FOC","EHMUV52TNDNHLYFJCM9IBEN4OX2DF4BU","SI59T7S7WO2PKBS5Z74PK6FUR74FTUHZ",...,"58H3OHIFVED30SLICYT6T2MC0K76YTTY","4KZTJJNG94FFI5MZQQEL13AS7H05QHCS","E1GF7Q53JQFP9P7OPCFWTVU347REO5MY","T5V0A00ZHKWHNLAD7N8H7OJS3QEZ7FFT","JLVV84D63Q0VME4OT7CW6UQR7M3AM86H"],["JEXTE9UKGO4GOXR28RR3KGCZZ4Z018QG","77GUIRRRPEMM5C7KVV3Y754R2LX5SWBB","YDTOG5PWVPV46D0EKL7BBY43JJV8KBYP","Z0QPAB52BXBJAP4BA8SMT8JWF9AI2QXK","DG72Z3A7C7WRUTKRTYR8SB6OZAOZN4J5",...,"R3B5BD3P5TRQAW323WTXEO4MRX0L02KG","SNN1TZ879D96ILJ556FA5LD9CYXBLH3D","IY7ZRT3M71740WXMOMGSO02NX1XE82FX","4T968C7JPNQWXL5L0O0A0TLXT8SX1UJG","2DG8AU6GLXRCHTIJA88B009YWI8GIOAC"]]